<template>
  <div class="restock-view">
    <div class="view-header">
      <div class="header-left">
        <h2>
          <span class="icon">🛒</span>
          补货清单
        </h2>
        <p class="subtitle">管理用品采购，库存不足时自动提醒，采购完成后自动回写库存</p>
      </div>
      <div class="header-actions">
        <button class="btn btn-primary" @click="openAddModal">
          + 新增补货项
        </button>
        <button class="btn btn-info" @click="handleAutoGenerate">
          🔄 智能生成补货清单
        </button>
        <button class="btn btn-outline btn-sm" @click="handleRefresh">
          刷新估算
        </button>
      </div>
    </div>

    <div class="summary-cards">
      <div class="summary-card blue">
        <div class="card-num">{{ totalCount }}</div>
        <div class="card-label">补货项总数</div>
      </div>
      <div class="summary-card yellow">
        <div class="card-num">{{ pendingCount }}</div>
        <div class="card-label">待采购</div>
      </div>
      <div class="summary-card green">
        <div class="card-num">{{ purchasedCount }}</div>
        <div class="card-label">已采购</div>
      </div>
      <div class="summary-card purple">
        <div class="card-num">{{ autoGeneratedCount }}</div>
        <div class="card-label">系统自动生成</div>
      </div>
    </div>

    <div class="filter-card">
      <div class="filter-row">
        <div class="filter-item">
          <label>状态</label>
          <select v-model="filterStatus" class="select-sm">
            <option value="">全部状态</option>
            <option v-for="s in RESTOCK_STATUS_TYPES" :key="s.value" :value="s.value">{{ s.label }}</option>
          </select>
        </div>
        <div class="filter-item">
          <label>类别</label>
          <select v-model="filterCategory" class="select-sm">
            <option value="">全部类别</option>
            <option v-for="cat in SUPPLY_CATEGORIES" :key="cat" :value="cat">{{ cat }}</option>
          </select>
        </div>
        <div class="filter-item">
          <label>搜索</label>
          <input type="text" v-model="searchKeyword" class="select-sm" placeholder="输入用品名称搜索">
        </div>
        <div class="filter-actions">
          <button class="btn btn-outline btn-sm" @click="resetFilters">重置</button>
        </div>
      </div>
    </div>

    <div class="section-card">
      <h3 class="section-title">
        <span class="section-icon">📋</span>
        补货清单列表
        <span class="count-badge">{{ filteredItems.length }} 条</span>
      </h3>

      <div v-if="filteredItems.length === 0" class="empty-section">
        <p v-if="restockList.length === 0">暂无补货项，点击"智能生成补货清单"自动识别需要补货的用品</p>
        <p v-else>没有符合筛选条件的补货项</p>
      </div>
      <div v-else class="restock-table-wrap">
        <table class="data-table">
          <thead>
            <tr>
              <th>用品名称</th>
              <th>所属类别</th>
              <th>当前库存</th>
              <th>本周预计消耗</th>
              <th>预计缺口</th>
              <th>建议补货数量</th>
              <th>实际采购数量</th>
              <th>补货状态</th>
              <th>来源</th>
              <th>备注</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="item in filteredItems"
              :key="item.id"
              :class="{
                'row-insufficient': item.status === 'pending' && item.estimatedGap > 0,
                'row-purchased': item.status === 'purchased'
              }"
            >
              <td>
                <span class="item-name">{{ item.name }}</span>
              </td>
              <td>
                <span class="cat-badge" :class="getCatClass(item.category)">{{ item.category }}</span>
              </td>
              <td class="num">{{ item.currentStock }}</td>
              <td class="num">{{ item.weeklyUsage }}</td>
              <td class="num">
                <span :class="item.estimatedGap > 0 ? 'text-danger' : item.estimatedGap === 0 ? 'text-warning' : 'text-success'">
                  {{ item.estimatedGap > 0 ? '-' : '+' }}{{ Math.abs(item.estimatedGap) }}
                </span>
              </td>
              <td class="num strong">{{ item.suggestedQuantity }}</td>
              <td class="num">
                <span v-if="item.status === 'purchased'" class="text-success strong">{{ item.actualQuantity }}</span>
                <span v-else>{{ item.actualQuantity }}</span>
              </td>
              <td>
                <span class="status-tag" :style="{ backgroundColor: getRestockStatusColor(item.status) + '20', color: getRestockStatusColor(item.status) }">
                  {{ getRestockStatusLabel(item.status) }}
                </span>
              </td>
              <td>
                <span v-if="item.source === 'auto'" class="source-tag auto">🤖 系统生成</span>
                <span v-else-if="item.source === 'alert'" class="source-tag alert">⚠️ 异常提醒</span>
                <span v-else-if="item.source === 'estimate'" class="source-tag estimate">📊 估算添加</span>
                <span v-else class="source-tag manual">✍️ 手动添加</span>
              </td>
              <td class="notes-cell">
                <span class="notes-text" :title="item.notes">{{ item.notes || '-' }}</span>
              </td>
              <td>
                <div class="action-buttons">
                  <template v-if="item.status === 'pending'">
                    <button class="icon-btn success small" @click="openPurchaseModal(item)">
                      ✓ 采购完成
                    </button>
                    <button class="icon-btn small" @click="openEditModal(item)">
                      编辑
                    </button>
                    <button class="icon-btn warning small" @click="handleCancel(item.id)">
                      取消
                    </button>
                    <button class="icon-btn danger small" @click="handleDelete(item.id)">
                      删除
                    </button>
                  </template>
                  <template v-else-if="item.status === 'purchased'">
                    <button class="icon-btn small" @click="handleReopen(item.id)">
                      ↶ 撤销采购
                    </button>
                    <button class="icon-btn danger small" @click="handleDelete(item.id)">
                      删除
                    </button>
                  </template>
                  <template v-else>
                    <button class="icon-btn success small" @click="handleReopen(item.id)">
                      重新开启
                    </button>
                    <button class="icon-btn danger small" @click="handleDelete(item.id)">
                      删除
                    </button>
                  </template>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="section-card">
      <h3 class="section-title">
        <span class="section-icon">💡</span>
        补货提示
      </h3>
      <div class="tips-grid">
        <div class="tip-card info">
          <h4>智能补货规则</h4>
          <ul>
            <li>库存不足以满足本周预计消耗时，自动生成补货项</li>
            <li>预计本周消耗后库存 ≤ 2 时，自动生成补货项</li>
            <li>当前库存 ≤ 2 时，自动生成补货项</li>
            <li>建议补货数量 = 缺口 × 1.5（向上取整），确保有安全库存</li>
          </ul>
        </div>
        <div class="tip-card warning">
          <h4>采购后自动操作</h4>
          <ul>
            <li>标记采购完成后，自动回写库存数量</li>
            <li>自动刷新异常提醒状态</li>
            <li>自动更新用品估算结果</li>
            <li>执行记录关联数据同步刷新</li>
          </ul>
        </div>
        <div class="tip-card success">
          <h4>快捷入口</h4>
          <ul>
            <li>在"异常提醒"中，可一键将库存不足项加入补货清单</li>
            <li>在"本周用品估算"中，可一键将需关注项加入补货清单</li>
            <li>支持随时手动新增任意用品的补货需求</li>
          </ul>
        </div>
      </div>
    </div>

    <div v-if="showFormModal" class="modal-overlay" @click.self="closeFormModal">
      <div class="modal">
        <div class="modal-header">
          <h3>{{ editingItem ? '编辑补货项' : '新增补货项' }}</h3>
          <button class="close-btn" @click="closeFormModal">×</button>
        </div>
        <div class="modal-body">
          <div class="form-grid">
            <div class="form-item full">
              <label>用品名称 *</label>
              <input list="supplyNames" type="text" v-model="formData.name" placeholder="输入用品名称">
              <datalist id="supplyNames">
                <option v-for="inv in inventories" :key="inv.name" :value="inv.name"></option>
              </datalist>
            </div>
            <div class="form-item">
              <label>所属类别</label>
              <select v-model="formData.category">
                <option v-for="cat in SUPPLY_CATEGORIES" :key="cat" :value="cat">{{ cat }}</option>
              </select>
            </div>
            <div class="form-item">
              <label>实际采购数量</label>
              <input type="number" v-model.number="formData.actualQuantity" min="1">
            </div>
            <div class="form-item full">
              <label>备注</label>
              <textarea v-model="formData.notes" rows="2" placeholder="补货备注信息"></textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-default" @click="closeFormModal">取消</button>
          <button class="btn btn-primary" @click="saveForm">保存</button>
        </div>
      </div>
    </div>

    <div v-if="showPurchaseModal" class="modal-overlay" @click.self="closePurchaseModal">
      <div class="modal">
        <div class="modal-header">
          <h3>确认采购完成</h3>
          <button class="close-btn" @click="closePurchaseModal">×</button>
        </div>
        <div class="modal-body">
          <div class="purchase-info">
            <p><strong>用品：</strong>{{ purchaseItem?.name }}</p>
            <p><strong>类别：</strong>{{ purchaseItem?.category }}</p>
            <p><strong>当前库存：</strong>{{ purchaseItem?.currentStock }}</p>
            <p><strong>建议补货数量：</strong>{{ purchaseItem?.suggestedQuantity }}</p>
          </div>
          <div class="warning-notice">
            ⚠️ 确认采购完成后，将自动更新库存并刷新所有关联数据
          </div>
          <div class="form-item">
            <label>实际采购数量 *</label>
            <input type="number" v-model.number="purchaseForm.actualQuantity" min="1">
          </div>
          <div class="form-item">
            <label>采购备注</label>
            <textarea v-model="purchaseForm.purchaseNotes" rows="2" placeholder="采购渠道、价格等备注"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-default" @click="closePurchaseModal">取消</button>
          <button class="btn btn-success" @click="confirmPurchase">✓ 确认采购完成</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from 'vue'
import {
  restockList,
  inventories,
  SUPPLY_CATEGORIES,
  RESTOCK_STATUS_TYPES,
  addRestockItem,
  updateRestockItem,
  deleteRestockItem,
  markRestockPurchased,
  cancelRestockItem,
  reopenRestockItem,
  autoGenerateRestockItems,
  refreshRestockItemEstimates,
  getRestockStatusLabel,
  getRestockStatusColor
} from '../composables/usePetStore'

const filterStatus = ref('')
const filterCategory = ref('')
const searchKeyword = ref('')

const showFormModal = ref(false)
const editingItem = ref(null)
const formData = reactive({
  name: '',
  category: '其他',
  actualQuantity: 1,
  notes: ''
})

const showPurchaseModal = ref(false)
const purchaseItem = ref(null)
const purchaseForm = reactive({
  actualQuantity: 1,
  purchaseNotes: ''
})

const totalCount = computed(() => restockList.value.length)
const pendingCount = computed(() => restockList.value.filter(r => r.status === 'pending').length)
const purchasedCount = computed(() => restockList.value.filter(r => r.status === 'purchased').length)
const autoGeneratedCount = computed(() => restockList.value.filter(r => r.source === 'auto').length)

const filteredItems = computed(() => {
  return restockList.value.filter(item => {
    if (filterStatus.value && item.status !== filterStatus.value) return false
    if (filterCategory.value && item.category !== filterCategory.value) return false
    if (searchKeyword.value && !item.name.includes(searchKeyword.value)) return false
    return true
  }).sort((a, b) => {
    if (a.status === 'pending' && b.status !== 'pending') return -1
    if (a.status !== 'pending' && b.status === 'pending') return 1
    if (a.estimatedGap !== b.estimatedGap) return b.estimatedGap - a.estimatedGap
    return new Date(b.createdAt) - new Date(a.createdAt)
  })
})

function getCatClass(category) {
  const map = {
    '食品': 'food',
    '清洁用品': 'clean',
    '美容用品': 'beauty',
    '玩具': 'toy',
    '药品': 'medicine'
  }
  return map[category] || 'other'
}

function resetFilters() {
  filterStatus.value = ''
  filterCategory.value = ''
  searchKeyword.value = ''
}

function openAddModal() {
  editingItem.value = null
  formData.name = ''
  formData.category = '其他'
  formData.actualQuantity = 1
  formData.notes = ''
  showFormModal.value = true
}

function openEditModal(item) {
  editingItem.value = item
  formData.name = item.name
  formData.category = item.category
  formData.actualQuantity = item.actualQuantity
  formData.notes = item.notes
  showFormModal.value = true
}

function closeFormModal() {
  showFormModal.value = false
  editingItem.value = null
}

function saveForm() {
  if (!formData.name.trim()) {
    alert('请输入用品名称')
    return
  }
  if (editingItem.value) {
    updateRestockItem(editingItem.value.id, {
      name: formData.name,
      category: formData.category,
      actualQuantity: formData.actualQuantity,
      notes: formData.notes
    })
  } else {
    addRestockItem({
      name: formData.name,
      category: formData.category,
      actualQuantity: formData.actualQuantity,
      notes: formData.notes,
      source: 'manual'
    })
  }
  closeFormModal()
}

function openPurchaseModal(item) {
  purchaseItem.value = item
  purchaseForm.actualQuantity = item.actualQuantity
  purchaseForm.purchaseNotes = ''
  showPurchaseModal.value = true
}

function closePurchaseModal() {
  showPurchaseModal.value = false
  purchaseItem.value = null
}

function confirmPurchase() {
  if (!purchaseItem.value) return
  const result = markRestockPurchased(purchaseItem.value.id, {
    actualQuantity: purchaseForm.actualQuantity,
    purchaseNotes: purchaseForm.purchaseNotes
  })
  if (result.success) {
    window.alert(result.message)
    closePurchaseModal()
  } else {
    window.alert(result.message)
  }
}

function handleCancel(id) {
  if (window.confirm('确定取消这个补货项？')) {
    cancelRestockItem(id)
  }
}

function handleReopen(id) {
  if (window.confirm('重新开启后，如果该补货项已采购，将扣减对应的库存。确定继续？')) {
    reopenRestockItem(id)
  }
}

function handleDelete(id) {
  if (window.confirm('确定删除这个补货项？')) {
    deleteRestockItem(id)
  }
}

function handleAutoGenerate() {
  const generated = autoGenerateRestockItems()
  if (generated.length > 0) {
    window.alert(`智能生成成功！新增 ${generated.length} 条补货项`)
  } else {
    window.alert('当前所有用品库存充足，无需补货 🎉')
  }
}

function handleRefresh() {
  refreshRestockItemEstimates()
  window.alert('估算数据已刷新')
}
</script>

<style scoped>
.restock-view {
  display: flex;
  flex-direction: column;
  gap: 20px;
}

.view-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-end;
  gap: 20px;
  flex-wrap: wrap;
}

.header-left h2 {
  margin: 0 0 6px 0;
  font-size: 22px;
  color: #111827;
  display: flex;
  align-items: center;
  gap: 10px;
}

.icon { font-size: 24px; }

.subtitle {
  margin: 0;
  color: #6b7280;
  font-size: 14px;
}

.header-actions {
  display: flex;
  gap: 8px;
  flex-wrap: wrap;
}

.summary-cards {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 14px;
}

.summary-card {
  background: #fff;
  border-radius: 12px;
  padding: 18px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
  text-align: center;
  border-top: 4px solid #9ca3af;
}
.summary-card.blue { border-top-color: #3b82f6; }
.summary-card.yellow { border-top-color: #f59e0b; }
.summary-card.green { border-top-color: #10b981; }
.summary-card.purple { border-top-color: #8b5cf6; }

.card-num {
  font-size: 32px;
  font-weight: 700;
  color: #111827;
  line-height: 1.2;
}
.summary-card.yellow .card-num { color: #d97706; }
.summary-card.green .card-num { color: #059669; }
.summary-card.purple .card-num { color: #7c3aed; }

.card-label {
  margin-top: 6px;
  font-size: 13px;
  color: #6b7280;
}

.filter-card {
  background: #fff;
  border-radius: 12px;
  padding: 16px 20px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}

.filter-row {
  display: flex;
  align-items: flex-end;
  gap: 14px;
  flex-wrap: wrap;
}

.filter-item {
  display: flex;
  flex-direction: column;
  gap: 4px;
  flex: 1;
  min-width: 140px;
}

.filter-item label {
  font-size: 12px;
  font-weight: 500;
  color: #6b7280;
}

.select-sm {
  padding: 6px 12px;
  border: 1px solid #e5e7eb;
  border-radius: 6px;
  font-size: 13px;
  background: #fff;
  cursor: pointer;
}

.filter-actions {
  display: flex;
  gap: 8px;
}

.btn {
  padding: 8px 16px;
  border: none;
  border-radius: 6px;
  font-size: 13px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-sm {
  padding: 6px 12px;
  font-size: 12px;
}

.btn-primary {
  background: #3b82f6;
  color: #fff;
}
.btn-primary:hover { background: #2563eb; }

.btn-success {
  background: #10b981;
  color: #fff;
}
.btn-success:hover { background: #059669; }

.btn-info {
  background: #8b5cf6;
  color: #fff;
}
.btn-info:hover { background: #7c3aed; }

.btn-default {
  background: #f3f4f6;
  color: #374151;
}
.btn-default:hover { background: #e5e7eb; }

.btn-outline {
  background: transparent;
  border: 1px solid #d1d5db;
  color: #374151;
}
.btn-outline:hover { background: #f9fafb; }

.btn-warning {
  background: #f59e0b;
  color: #fff;
}
.btn-warning:hover { background: #d97706; }

.btn-danger {
  background: #ef4444;
  color: #fff;
}
.btn-danger:hover { background: #dc2626; }

.section-card {
  background: #fff;
  border-radius: 12px;
  padding: 20px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.06);
}

.section-title {
  margin: 0 0 16px 0;
  font-size: 16px;
  color: #111827;
  display: flex;
  align-items: center;
  gap: 8px;
  padding-bottom: 12px;
  border-bottom: 1px solid #f3f4f6;
}

.section-icon { font-size: 18px; }

.count-badge {
  margin-left: 8px;
  padding: 2px 10px;
  background: #eff6ff;
  color: #2563eb;
  border-radius: 10px;
  font-size: 12px;
  font-weight: 500;
}

.empty-section {
  padding: 40px 20px;
  text-align: center;
  color: #9ca3af;
  font-size: 14px;
}

.restock-table-wrap {
  overflow-x: auto;
}

.data-table {
  width: 100%;
  border-collapse: collapse;
  font-size: 13px;
}

.data-table th,
.data-table td {
  padding: 12px 14px;
  text-align: left;
  border-bottom: 1px solid #f3f4f6;
}

.data-table th {
  background: #f9fafb;
  font-weight: 600;
  color: #374151;
  font-size: 12px;
  white-space: nowrap;
}

.data-table tbody tr:hover {
  background: #f9fafb;
}

.data-table tr.row-insufficient {
  background: #fef2f2;
}
.data-table tr.row-insufficient:hover {
  background: #fee2e2;
}
.data-table tr.row-purchased {
  background: #ecfdf5;
}
.data-table tr.row-purchased:hover {
  background: #d1fae5;
}

.data-table td.num {
  text-align: right;
  font-variant-numeric: tabular-nums;
}
.data-table td.num.strong {
  font-weight: 600;
  color: #1f2937;
}

.text-danger { color: #dc2626; font-weight: 600; }
.text-warning { color: #d97706; font-weight: 600; }
.text-success { color: #059669; font-weight: 600; }
.text-muted { color: #9ca3af; }

.item-name {
  font-weight: 500;
  color: #1f2937;
}

.cat-badge {
  display: inline-block;
  padding: 3px 10px;
  border-radius: 10px;
  font-size: 11px;
  font-weight: 500;
}
.cat-badge.food { background: #fef3c7; color: #92400e; }
.cat-badge.clean { background: #dbeafe; color: #1e40af; }
.cat-badge.beauty { background: #fce7f3; color: #9d174d; }
.cat-badge.toy { background: #ddd6fe; color: #5b21b6; }
.cat-badge.medicine { background: #fecaca; color: #991b1b; }
.cat-badge.other { background: #e5e7eb; color: #374151; }

.status-tag {
  display: inline-block;
  padding: 4px 10px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 500;
}

.source-tag {
  display: inline-block;
  padding: 2px 8px;
  border-radius: 6px;
  font-size: 11px;
  font-weight: 500;
}
.source-tag.auto { background: #ede9fe; color: #6d28d9; }
.source-tag.alert { background: #fef2f2; color: #dc2626; }
.source-tag.estimate { background: #dbeafe; color: #2563eb; }
.source-tag.manual { background: #f3f4f6; color: #4b5563; }

.notes-cell {
  max-width: 150px;
}

.notes-text {
  font-size: 12px;
  color: #6b7280;
  display: -webkit-box;
  -webkit-line-clamp: 2;
  -webkit-box-orient: vertical;
  overflow: hidden;
}

.action-buttons {
  display: flex;
  gap: 4px;
  flex-wrap: wrap;
}

.icon-btn {
  padding: 4px 10px;
  border: 1px solid #e5e7eb;
  background: #fff;
  border-radius: 4px;
  font-size: 12px;
  cursor: pointer;
  color: #374151;
}
.icon-btn:hover { background: #f9fafb; }
.icon-btn.success {
  color: #059669;
  border-color: #a7f3d0;
}
.icon-btn.success:hover { background: #ecfdf5; }
.icon-btn.warning {
  color: #d97706;
  border-color: #fde68a;
}
.icon-btn.warning:hover { background: #fffbeb; }
.icon-btn.danger {
  color: #dc2626;
  border-color: #fecaca;
}
.icon-btn.danger:hover { background: #fef2f2; }
.icon-btn.small {
  padding: 3px 8px;
  font-size: 11px;
}

.tips-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
  gap: 14px;
}

.tip-card {
  border-radius: 10px;
  padding: 16px;
  border-left: 4px solid #9ca3af;
}
.tip-card.info {
  background: #eff6ff;
  border-left-color: #3b82f6;
}
.tip-card.warning {
  background: #fffbeb;
  border-left-color: #f59e0b;
}
.tip-card.success {
  background: #ecfdf5;
  border-left-color: #10b981;
}

.tip-card h4 {
  margin: 0 0 10px 0;
  font-size: 14px;
  color: #1f2937;
}

.tip-card ul {
  margin: 0;
  padding-left: 18px;
  font-size: 13px;
  color: #374151;
  line-height: 1.8;
}

.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  padding: 20px;
}

.modal {
  background: #fff;
  border-radius: 16px;
  width: 100%;
  max-width: 520px;
  max-height: 90vh;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.modal-header {
  padding: 18px 24px;
  border-bottom: 1px solid #f3f4f6;
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.modal-header h3 {
  margin: 0;
  font-size: 18px;
  color: #111827;
}

.close-btn {
  width: 32px;
  height: 32px;
  border: none;
  background: #f3f4f6;
  border-radius: 8px;
  font-size: 20px;
  cursor: pointer;
  color: #6b7280;
  line-height: 1;
}
.close-btn:hover { background: #e5e7eb; }

.modal-body {
  padding: 24px;
  overflow-y: auto;
  flex: 1;
}

.modal-footer {
  padding: 16px 24px;
  border-top: 1px solid #f3f4f6;
  display: flex;
  justify-content: flex-end;
  gap: 10px;
}

.form-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 16px;
}

.form-item {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.form-item.full {
  grid-column: 1 / -1;
}

.form-item label {
  font-size: 13px;
  font-weight: 500;
  color: #374151;
}

.form-item input,
.form-item select,
.form-item textarea {
  padding: 8px 12px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 14px;
  outline: none;
  transition: border-color 0.2s;
  font-family: inherit;
}
.form-item input:focus,
.form-item select:focus,
.form-item textarea:focus {
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59, 130, 246, 0.1);
}

.purchase-info {
  background: #f9fafb;
  padding: 12px 16px;
  border-radius: 8px;
  margin-bottom: 12px;
}
.purchase-info p {
  font-size: 13px;
  color: #374151;
  line-height: 1.8;
  margin: 0;
}

.warning-notice {
  background: #fffbeb;
  border: 1px solid #fde68a;
  color: #92400e;
  padding: 10px 14px;
  border-radius: 8px;
  font-size: 13px;
  margin-bottom: 16px;
}

@media (max-width: 768px) {
  .summary-cards {
    grid-template-columns: repeat(2, 1fr);
  }
  .form-grid {
    grid-template-columns: 1fr;
  }
  .view-header {
    flex-direction: column;
    align-items: stretch;
  }
  .header-actions {
    justify-content: flex-start;
  }
}
</style>
